### ISSUE TITLE
Add "TAB" (and click outside(?)) as a shortcut to accept updates to inline fields

### ISSUE THREAD

**Issue by kino90** [intesys/ytestbook#78]
For example, when adding `TestCases` inline, pressing the `Tab` key should also save the values (like the `Enter` key does)

The same behaviour should occurr _(maybe ?)_ also when clicking outside (before hiding the form) 

`Esc` key is actually closing the form WITHOUT saving (and that's OK)

This was reported to me by @ebordoni

**Comment by nicolabosco87** [comment]
done in https://github.com/intesys/ytestbook/pull/87
